# Generated by Django 5.0.3 on 2025-01-06 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrace_farming_app', '0003_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='terrace_farming_app.seller'),
        ),
    ]
