# Generated by Django 5.0.3 on 2025-01-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrace_farming_app', '0004_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.ImageField(upload_to=''),
        ),
    ]
