# Generated by Django 5.0.3 on 2025-01-07 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terrace_farming_app', '0007_remove_cart_owner_remove_cart_status_cart_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='amount',
        ),
    ]
