# Generated by Django 5.0.3 on 2025-01-08 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrace_farming_app', '0009_alter_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='terrace_farming_app.delivery_boy'),
        ),
    ]
