# Generated by Django 5.0.3 on 2025-01-08 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrace_farming_app', '0010_orders_delivery_boy'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_boy',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='terrace_farming_app.users'),
        ),
    ]
