# Generated by Django 5.0.3 on 2025-01-09 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terrace_farming_app', '0011_delivery_boy_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_boy',
            name='user',
        ),
    ]
