# Generated by Django 5.0.3 on 2025-01-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrace_farming_app', '0013_alter_orders_delivery_boy_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sender',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
